### ISSUE TITLE
Request for scATAC-seq data cell type information 

### ISSUE THREAD

**Issue by dannihong** [GreenleafLab/scScalpChromatin#3]
Hi, 

I am particularly interested in the scATAC-seq data you generated as part of your study. To further my research, I would like to request access to the metadata information (such as cell type annotation) from your  scATAC-seq dataset. These files would be incredibly valuable for my analysis.

Thanks!

**Comment by boberrey** [comment]
Hello,

Thank you for your interest in our work! The cell type (cluster) annotation information for the scATAC-seq dataset is provided in Table S2 of the paper. Table S3 has the scRNA-seq cell type annotations if you need those as well. I will also upload the supplemental tables to Google Drive here: (https://drive.google.com/drive/folders/1klScH010LvYxdU-TZiSkGVip9IrilZN2?usp=sharing) if you don't have access to them through the Nature Genetics link.

Best of luck!
