### ISSUE TITLE
LinkageScores

### ISSUE THREAD

**Issue by smithsl** [GreenleafLab/scScalpChromatin#4]
Hi,

Thanks you for sharing these great scripts.
I’m trying to reproduce figures similar to yours in Suppl Fig 6F-H (identifying putative gene targets of transcription factors). 

When calculating the LinkageScore, where does the motif score come from? 
Apologies if I’ve missed this explanation somewhere.

For TFs of interest, I’m extracting the motifs frequency matrix from JASPAR2020 and then using Biostrings matchPWM function to return any matches which meet a certain threshold. The output of this gives me a score of how well it matches. This is what I’ve been using in the LinkageScore calculation – is that correct.

TIA.

**Comment by boberrey** [comment]
Hello! 

In our implementation, the motif score is coming from [ChromVAR](https://greenleaflab.github.io/chromVAR/articles/Introduction.html) which uses [motifmatchr](https://greenleaflab.github.io/motifmatchr/index.html) to identify motif positions, which itself is using the MOODS library, which uses a [log-odds scoring system](https://github.com/jhkorhonen/MOODS/wiki/Brief-theoretical-introduction) for scoring how likely a given motif match 'matches' the motif PWM. It sounds like what you are doing would likely give a similar type of metric.

Hope this is helpful!

**Comment by smithsl** [comment]
That's great! Thanks for replying.
